version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Project Directory
          command: cd stock-tracker
      - run:
          name: Install Dependancies
          command: pwd && ls -a
      - run:
          name: Run Tests
          command: npm run test
